const tarotCocktailMap = {
    "The Fool": "Vodka Martini",
    "The Magician": "Long Island Iced Tea",
    "The High Priestess": "Cosmopolitan",
    "The Empress": "Bloody Mary",
    "The Emperor": "Old Fashioned",
    "The Hierophant": "Mai Tai",
    "The Lovers": "Sex on the Beach",
    "The Chariot": "Mojito",
    "Strength": "Whiskey Sour",
    "The Hermit": "Gin and Tonic",
    "Wheel of Fortune": "Pina Colada",
    "Justice": "White Russian",
    "The Hanged Man": "Tequila Sunrise",
    "Death": "Dark and Stormy",
    "Temperance": "Margarita",
    "The Devil": "Satan's Whiskers",
    "The Tower": "Irish Car Bomb",
    "The Star": "Blue Lagoon",
    "The Moon": "Black Russian",
    "The Sun": "Screwdriver",
    "Judgment": "Godfather",
    "The World": "Gin Fizz",
    "Ace of Cups": "Rum Punch",
    "Two of Cups": "Pisco Sour",
    "Three of Cups": "Frozen Daiquiri",
    "Four of Cups": "White Sangria",
    "Five of Cups": "Red Sangria",
    "Six of Cups": "Strawberry Daiquiri",
    "Seven of Cups": "Amaretto Sour",
    "Eight of Cups": "Negroni",
    "Nine of Cups": "French 75",
    "Ten of Cups": "Champagne Cocktail",
    "Page of Cups": "Bellini",
    "Knight of Cups": "Mint Julep",
    "Queen of Cups": "Kir Royale",
    "King of Cups": "Paloma",
    "Ace of Pentacles": "Moscow Mule",
    "Two of Pentacles": "Sazerac",
    "Three of Pentacles": "Manhattan",
    "Four of Pentacles": "Gimlet",
    "Five of Pentacles": "Aperol Spritz",
    "Six of Pentacles": "Tom Collins",
    "Seven of Pentacles": "Caipirinha",
    "Eight of Pentacles": "Gin Gimlet",
    "Nine of Pentacles": "Sidecar",
    "Ten of Pentacles": "Mimosa",
    "Page of Pentacles": "White Lady",
    "Knight of Pentacles": "Vesper",
    "Queen of Pentacles": "Corpse Reviver",
    "King of Pentacles": "Blackberry Smash",
    "Ace of Swords": "Martinez",
    "Two of Swords": "Dark and Stormy",
    "Three of Swords": "Singapore Sling",
    "Four of Swords": "French 75",
    "Five of Swords": "Vieux Carré",
    "Six of Swords": "Zombie",
    "Seven of Swords": "Harvey Wallbanger",
    "Eight of Swords": "Paloma",
    "Nine of Swords": "Pisco Sour",
    "Ten of Swords": "Jack Rose",
    "Page of Swords": "Blood and Sand",
    "Knight of Swords": "Ramos Gin Fizz",
    "Queen of Swords": "Hemingway Daiquiri",
    "King of Swords": "Vesper",
    "Ace of Wands": "Mai Tai",
    "Two of Wands": "Aperol Spritz",
    "Three of Wands": "Negroni",
    "Four of Wands": "Pisco Sour",
    "Five of Wands": "Pina Colada",
    "Six of Wands": "Margarita",
    "Seven of Wands": "Tom Collins",
    "Eight of Wands": "Manhattan",
    "Nine of Wands": "Whiskey Sour",
    "Ten of Wands": "Old Fashioned",
    "Page of Wands": "Moscow Mule",
    "Knight of Wands": "Mojito",
    "Queen of Wands": "Sazerac",
    "King of Wands": "Dark and Stormy",
}
